### ISSUE TITLE
Configuration of service port and targetPort

### ISSUE THREAD

**Issue by mhyllander** [haproxy-ingress/charts#25]
I was just bitten by a configuration issue that occurred when I upgraded from the incubator version of this chart. In the incubator version of the chart, the service ports were configured like this:

```yaml
  service:
    httpPorts:
      - port: 80
    httpsPorts:
      - port: 443
      - port: 8443
```

In the current chart, you are required to also specify the `targetPort`, like this:

```yaml
  service:
    httpPorts:
      - port: 80
        targetPort: http
    httpsPorts:
      - port: 443
        targetPort: https
      - port: 8443
        targetPort: https
```

Unless I'm mistaken, haproxy is only listening on two ports, `http` (80) and `https` (443). Since I didn't notice this difference between the charts and still had my original configuration, kubernetes silently assumed that `targetPort` is the same as `port`. This of course broke things, since haproxy is not listening on port 8443.

The incubator chart assumed that all ports under the `httpPorts` key should have `targetPort: http`, and all ports under the `httpsPorts` key should have `targetPort: https`. Is there any reason why the `targetPort` is required now? It seems to be redundant.
