### ISSUE TITLE
haproxy metrics exposed by defaultBackend by ingress

### ISSUE THREAD

**Issue by buker** [haproxy-ingress/charts#30]
I have issue that metrics of haproxy or haproxy-ingress are exposed to ingress on path /metrics. They shouldn't be exposed external by defaultBackend.

Values:
```
  defaultBackend:
    enabled: true
    resources:
      limits:
        cpu: 20m
        memory: 20Mi
      requests:
        cpu: 20m
        memory: 20Mi
    replicaCount: 2
  controller:
    haproxy:
      enabled: enabled
      image:
        repository: haproxy
        tag: "2.3.12"
        pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 2
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 128Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 50
    serviceMonitor:
      enabled: true
    ingressClass: haproxy
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
          topologyKey: "kubernetes.io/hostname"
    extraArgs:
      publish-service: "haproxy-ingress/haproxy-ingress"
    securityContext:
      sysctls:
      - name: net.ipv4.ip_local_port_range
        value: "1024 65535"
    livenessProbe:
      failureThreshold: 10
    service:
      type: LoadBalancer  
      labels:
        app.kubernetes.io/release: haproxy-ingress
    stats:
      enabled: true
    metrics:
      enabled: true
      embaded: false
    config:
      timeout-keep-alive: 620s
      config-global: |
        tune.bufsize 32768
        tune.maxrewrite 8192
      config-defaults: |
        option redispatch
      securityContext:
        privileged: true
```

Metrics are available on 

http://ingress-domain.com/metrics

When ingress object has defined path /metrics it will display app metrics
