### ISSUE TITLE
create an IngressClass resource

### ISSUE THREAD

**Issue by jouve** [haproxy-ingress/charts#32]
Hi,

it would be nice if the chart allowed to create an IngressClass resource, something like:

```yaml
controller:
  ingressClass: haproxy  # existing .Values
  ingressClassResource:  # new .Values
    enabled: false
    controller: haproxy-ingress.github.io/controller
```

and 
```yaml
{{- if .Values.controller.ingressClassResource.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClass }}
spec:
  controller: {{ .Values.ingressClassResource.controller }}
{{- end }}
``` 

+ adding ` --controller-class {{ .Values.ingressClassResource.controller }}` to the pod template.

ref: 
https://haproxy-ingress.github.io/docs/configuration/keys/#class-matter
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L98
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-ingressclass.yaml

what do you think ?
