### ISSUE TITLE
How to use it as a DaemonSet with hostNetwork? - bug in chart ?

### ISSUE THREAD

**Issue by ieugen** [haproxy-ingress/charts#4]
Hi, 

I'm trying to figure out how to use haproxy-ingress as a DaemonSet with hostNetwork so it listens on 80 and 443 on all my nodes.

I have the following config: 
```
    controller:
      hostNetwork: true
      kind: DaemonSet
      daemonset:
        useHostPort: true
      config:
        use-proxy-protocol: "true"
```

And I get a LoadBalancer type service listening on high ports. 

```
 k get svc 
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
haproxy-ingress   LoadBalancer   10.43.190.56   <pending>     80:31738/TCP,443:30543/TCP   13m
```
