### ISSUE TITLE
support for topologyspreadconstraint?

### ISSUE THREAD

**Issue by taxilian** [haproxy-ingress/charts#40]
Hi,

Could you add support for `topologySpreadConstraint` for the Deployment in the helm chart? In my bare metal cluster I often want to keep processing as spread out amongst systems as possible -- and I definitely want to ensure that I don't end up with all of my ingress controllers on the same system in case it goes out somehow -- so I often use something like this in my Deployment:

```
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            k8s-app: myappname
```

That tells it to try to keep the same number of pods on each node, +/- 1 (maxSkew). Something similar can be done with podAffinity by setting an antiAffinity, but then if it autoscales to more instances than I have nodes the processes can't be started up. I don't see any way to add this with helm, though, so to use it I have to edit the deployment after deploying the chart -- and that'll become a problem when/if I want to upgrade.

I could make the change and submit a PR, but I have zero experience with golang or writing helm charts and I honestly have no idea how to do it.
