### ISSUE TITLE
when user deamonset and hostnetwork,is this a bug?

### ISSUE THREAD

**Issue by usernameisnull** [haproxy-ingress/charts#42]
- command
```shell
helm install haproxy-ingress haproxy-ingress-0.13.3.tgz  --create-namespace --namespace ingress-controller  -f haproxy-ingress-values.yaml
```
-  haproxy-ingress-values.yaml
```yaml
controller:
  daemonset:
    useHostPort: true
    hostPorts:
      http: 8090
      https: 4433
  #service:
  #  httpPorts:
  #    - port: 8090
  #      targetPort: http
  #  httpsPorts:
  #    - port: 4433
  #      targetPort: https
  haproxy:
    image:
      repository: harbor.enmotech.com/library/haproxy-ingress
      tag: v0.13.3
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  kind: DaemonSet
  nodeSelector: 
    haproxy-ingress-controller: "true"
```
- the error
```shell
Error: DaemonSet.apps "haproxy-ingress" is invalid: [spec.template.spec.containers[0].ports[0].containerPort: Invalid value: 80: must match `hostPort` when `hostNetwork` is true, spec.template.spec.containers[0].ports[1].containerPort: Invalid value: 443: must match `hostPort` when `hostNetwork` is true]
```
- question
   - when use hostnetwork, it use hostport automatically?
   - this is a bug? if not, when use deamoset and hostnetwork, how to change the port it listens?I don't want to listen 80 and 443!

**Comment by jcmoraisjr** [comment]
Hi, I can reproduce this, thanks for reporting. Currently containerPort is hardcoded, hence the error you saw. I'll fix this before the next release. In the mean time you can remove all the `daemonset:` parameter - listening to the host ports will always work despite the port configuration, the only problem is that Kubernetes wouldn't be aware of the listening port and can eventually run another workload that uses the same ports in hostNetwork mode and lead to a conflict in your ingress.

**Comment by jcmoraisjr** [comment]
We've now containerPorts that can be parameterized. Your config would look like something like this:

```yaml
controller:
  daemonset:
    useHostPort: true
    hostPorts:
      http: 8090
      https: 4433
  containerPorts:
    http: 8090
    https: 4433
  haproxy:
    image:
      repository: harbor.enmotech.com/library/haproxy-ingress
      tag: v0.13.3
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  kind: DaemonSet
  nodeSelector:
    haproxy-ingress-controller: "true"
```
