### ISSUE TITLE
Add a dedicated setting for the "publish-service" argument to the chart

### ISSUE THREAD

**Issue by itspngu** [haproxy-ingress/charts#51]
As discussed on [Slack](https://kubernetes.slack.com/archives/C01D8GKKT5H/p1654617776211139),

it would make sense to have a way to set the "publish-service" argument with a key in values.yaml; this option tells the controller where to fetch its public IP from so it can in turn populate the `status.loadBalancer.ingress[].ip` field(s) of the Ingress resource(s) it manages.

This can currently be achieved manually by adding `publish-service: <namespace>/<service>` to `controller.extraArgs` in values.yaml, which is not the greatest workaround because the installation namespace is passed to Helm and the service name is rendered by the chart itself, which means that users must assume some of the rendered output in advance and make it part of the values file itself, rather than having an idempotent option.

Care should be taken to not enable/set `publish-service` by default to not break existing setups, as well as setting up the yaml rendering process in such a way that any already-set value for `publish-service` (by means of specifying it in `controller.extraArgs`) is prioritized and thus preserved over the dedicated setting this issue calls for.

The following is a suggested syntax for the proposed setting, [inspired by how ingress-nginx handles the same issue](https://github.com/kubernetes/ingress-nginx/blob/fb2f00bae5c444b742f42e05eddf80a36dd6b7f8/charts/ingress-nginx/values.yaml#L138).

```yaml
# values.yaml

controller:
  # Allows customization of the source of the IP address or FQDN to report
  # in the ingress status field. If disabled (default), the status field remains 
  # unpopulated. If enabled, it reads the information provided by the service,
  # unless pathOverride is specified.
  publishService:
    # Enable 'publishService' or not
    enabled: false
    # Allows overriding of the publish service to bind to
    # Must be <namespace>/<service_name>
    pathOverride: ""
```
