### ISSUE TITLE
Broken support for some v1.25+ clusters

### ISSUE THREAD

**Issue by sanarena** [haproxy-ingress/charts#64]
HAProxy ingress installed fine on v1.25 cluster in our test system, however in another v1.25, it is showing this error:
 
`Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "haproxy-ingress" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"`

It seems like it is picking up v1beta1 by mistake instead of v1, [semverCompare could be buggy intercepting version numbers](https://github.com/pingidentity/helm-charts/issues/235).

**Comment by jcmoraisjr** [comment]
This happens because PSP was removed on cluster v1.25 and newer. Controller's helm chart installs PSP when you have rbac.security.enable as true in your configuration. We're removing that on clusters v1.25 or newer because there isn't a similar substitute. We'll instead make HAProxy Ingress less depend on privileged permissions so one can configure its namespace with one of the natively supported [Pod Security Admissions](https://kubernetes.io/docs/concepts/security/pod-security-standards/).

Master has already that update, which will be on newer v0.13, v0.14 and v0.15 controller releases.

**Comment by jr01** [comment]
We ran into the same error, but we didn't set rbac.security.enable and it's false by default.

We originally started with AKS v.1.24 and installed haproxy-ingress v0.13.7 which uses `policy/v1beta1` in `[controller-poddisruptionbudget.yaml](https://github.com/haproxy-ingress/charts/blob/0.13.7/haproxy-ingress/templates/controller-poddisruptionbudget.yaml).

Recently we upgraded to v1.26 and the pdb on the cluster apparently auto upgraded to use `policy/v1`:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    meta.helm.sh/release-name: haproxy-ingress
    meta.helm.sh/release-namespace: haproxy
  creationTimestamp: "2023-03-21T08:49:24Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: haproxy-ingress
    app.kubernetes.io/version: v0.13.7
    helm.sh/chart: haproxy-ingress-0.13.7
    ...
```

However helm upgrade with v0.13.7 started failing with
```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "haproxy-ingress" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

At first we attempted to upgrade to v0.13.8 ( also tried to upgrade to v0.14.4 ) which fixed the policy, however we got the same error!

in the end we managed to fix the error by running:
```
helm plugin install https://github.com/helm/helm-mapkubeapis
helm mapkubeapis -n haproxy haproxy-ingress
```

then `helm upgrade --install haproxy-ingress haproxy-ingress/haproxy-ingress --version v0.13.7 .... `  - and also higher chart versions work.
