### ISSUE TITLE
Bug: nodePort fails to apply to template

### ISSUE THREAD

**Issue by tadghh** [haproxy-ingress/charts#83]
The external IP applies correctly, not sure why the nodePort fails though.

command: 
```bash
helm template haproxy haproxytech/kubernetes-ingress -f haproxy-values.yaml --debug
```

haproxy-values:
```yaml
controller:
  enableStaticPorts: true
  service:
    type: NodePort
    httpPorts:
      - port: 80
        targetPort: http
        nodePort: 33333
    httpsPorts:
      - port: 443
        targetPort: https
        nodePort: 55555
    extraPorts:
      - port: 6060
        targetPort: prometheus
    externalIPs:
      - 192.168.1.100
```

result:
```yaml
---
# Source: kubernetes-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: haproxy-kubernetes-ingress
  namespace: default
  labels:
    app.kubernetes.io/name: kubernetes-ingress
    helm.sh/chart: kubernetes-ingress-1.40.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/version: 3.0.1
  annotations:
spec:

  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      appProtocol: http
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      appProtocol: https
      targetPort: https
    - name: quic
      port: 443
      protocol: UDP
      appProtocol: https
      targetPort: quic
    - name: stat
      port: 1024
      protocol: TCP
      targetPort: stat
    - name: prometheus
      port: 6060
      protocol: TCP
      targetPort: prometheus
  selector:
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/instance: haproxy
  externalIPs:
    - 192.168.1.100
```
